### ISSUE TITLE
Is SharpMath deterministic?

### ISSUE THREAD

**Issue by Krakean** [ProgTrade/SharpMath#5]
Hello.
Is this math library is deterministic? Can it be used for networked RTS, for example?

**Comment by ProgTrade** [comment]
Hello,

I do not really know what you mean by deterministic. Some functions may be implemented very slowly at the moment. So, I do not know, if it may be suitable for RTS.

Best,
Dominic

**Comment by NET-D3v3l0p3r** [comment]
I guess what he means is whether this library returns the same results on every platform.  
_

**Comment by ProgTrade** [comment]
Ah okay.
Well, to be honest, I did only test it on Windows. Should write some more unit tests and try it out on other paltforms as well.
