### ISSUE TITLE
Vector2.Transform(Matrix3x3) not taking translation into consideration.

### ISSUE THREAD

**Issue by chadiik** [ProgTrade/SharpMath#6]
Matrix3x3*Vector2 or the Vector2.Transform(Matrix3x3) method does not apply translation to the result.
`Matrix3x3 translation = Matrix3x3.Translation(10, 10);`
`Vector2 transformed = translation * Vector2.One; // transformed = Vector2(1, 1)`
Adding the translation components (matrix[2, 0] matrix[2, 1]) would give the expected result: `transformed = Vector2(1, 1)`

**Comment by ProgTrade** [comment]
Hi,

I am sorry. I did not get any notice from GitHub that this issue has been submitted. I will check that out immediately.

Best,
Dominic
